### ISSUE TITLE
Test VOT

### ISSUE THREAD

**Issue by jianjiandandande** [MegviiDetection/video_analyst#129]
When I test my trained models using VOT datasets, I always run into the following problems.

```
(vincent) ubuntu@ubun:~/Vincent/object_track/video_analyst-master$ python ./main/test.py --config 'experiments/siamfcpp/train/lasot/siamfcpp_googlenet-trn.yaml'
2020-07-22 17:03:57.370 | INFO     | __main__:<module>:65 - Load experiment configuration at: /home/ubuntu/Vincent/object_track/video_analyst-master/experiments/siamfcpp/train/lasot/siamfcpp_googlenet-trn.yaml
2020-07-22 17:03:57.764 | INFO     | videoanalyst.model.module_base:update_params:62 - Load pretrained SiamTrack parameters from: /home/ubuntu/Vincent/object_track/video_analyst-master/snapshots/siamfcpp_googlenet-lasot/epoch-19.pkl whose md5sum is fc8c27d28ac7585f2a4c9b7a848a6767
2020-07-22 17:03:57.768 | INFO     | videoanalyst.engine.tester.tester_impl.vot:run_tracker:98 - runing test on devices [device(type='cuda', index=0)]
2020-07-22 17:03:57.768 | INFO     | videoanalyst.engine.tester.tester_impl.vot:run_tracker:100 - Using dataset VOT2018 at: /home/ubuntu/Vincent/object_track/video_analyst-master/datasets/VOT/vot2018
  0%|                                                                                                                                                                                | 0/60 [00:00<?, ?it/s]Traceback (most recent call last):
  File "./main/test.py", line 80, in <module>
    tester.test()
  File "/home/ubuntu/Vincent/object_track/video_analyst-master/videoanalyst/engine/tester/tester_impl/vot.py", line 87, in test
    self.run_tracker()
  File "/home/ubuntu/Vincent/object_track/video_analyst-master/videoanalyst/engine/tester/tester_impl/vot.py", line 115, in run_tracker
    self.worker(keys, all_devs[0], result_queue, speed_queue)
  File "/home/ubuntu/Vincent/object_track/video_analyst-master/videoanalyst/engine/tester/tester_impl/vot.py", line 168, in worker
    lost, speed = self.track_single_video(tracker, video, v_id=v_id)
  File "/home/ubuntu/Vincent/object_track/video_analyst-master/videoanalyst/engine/tester/tester_impl/vot.py", line 232, in track_single_video
    package="vot_overlap").vot_overlap
  File "/home/ubuntu/anaconda3/envs/vincent/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/Vincent/object_track/video_analyst-master/videoanalyst/evaluation/vot_benchmark/pysot/utils/__init__.py", line 9, in <module>
    from . import region
ImportError: cannot import name 'region' from 'videoanalyst.evaluation.vot_benchmark.pysot.utils' (/home/ubuntu/Vincent/object_track/video_analyst-master/videoanalyst/evaluation/vot_benchmark/pysot/utils/__init__.py)
  0%|                                                                                                                                                                                | 0/60 [00:02<?, ?it/s]
```
Then , I found the file structure in the 'video_analyst-master/videoanalyst/evaluation/vot_benchmark/pysot/utils/' directory looks like this：

```
(vincent) ubuntu@ubun:~/Vincent/object_track/video_analyst-master/videoanalyst/evaluation/vot_benchmark/pysot/utils$ ls
c_region.pxd  __init__.py  misc.py  __pycache__  region.pyx  setup.py  src  statistics.py
```
This '. pyx 'file causes the direct use of the `from . import region` in `__init__.py` to fail

**Comment by lzx1413** [comment]
@jianjiandandande have you run the `bash compile.sh`?

**Comment by MARMOTatZJU** [comment]
@jianjiandandande Issue closed as it's been a long time without further reply. Wish that you've already fixed your issue. Feel free to reopen for further help

**Comment by chenrxi** [comment]
> @jianjiandandande have you run the `bash compile.sh`?

I have run the 'bash compile.sh', but it did not work and still met the same error

**Comment by wangjinbo0929** [comment]
@jianjiandandande Have you solved the problem yet

**Comment by wangjinbo0929** [comment]
@jianjiandandande I have the same problem and don't know how to solve it, thank you

**Comment by MARMOTatZJU** [comment]
@wangjinbo0929  Can you upload the output log of  `bash compile.sh`?

**Comment by MARMOTatZJU** [comment]
@chenrxi Can you upload the output log of  `bash compile.sh`?
