### ISSUE TITLE
Get error when run siamfcpp's scripts

### ISSUE THREAD

**Issue by lfxx** [MegviiDetection/video_analyst#169]
When i run the words below,i got the following error:
`python demo/main/video/sot_video.py --device cuda --video videos/bodou.mp4 --config "experiments/siamfcpp/test/vot/siamfcpp_googlenet_votlt.yaml"`
error:
```
Traceback (most recent call last):
  File "demo/main/video/sot_video.py", line 213, in <module>
    main(args)
  File "demo/main/video/sot_video.py", line 141, in main
    rect_pred = pipeline.update(frame)
  File "/home/longmao/workspace/video_analyst/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py", line 326, in update
    update_state=True)
  File "/home/longmao/workspace/video_analyst/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py", line 249, in track
    phase=phase_track)
  File "/data/.conda/envs/tracker/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/longmao/workspace/video_analyst/videoanalyst/model/task_model/taskmodel_impl/siamese_track.py", line 180, in forward
    c_out, r_out, search_img.size(-1))
  File "/data/.conda/envs/tracker/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/longmao/workspace/video_analyst/videoanalyst/model/task_head/taskhead_impl/track_head.py", line 139, in forward
    bbox = get_box(fm_ctr, offsets)
  File "/home/longmao/workspace/video_analyst/videoanalyst/model/task_head/taskhead_impl/track_head.py", line 57, in get_box
    xy0 = (xy_ctr[:, :, :] - offsets[:, :, :2])
RuntimeError: The size of tensor a (361) must match the size of tensor b (961) at non-singleton dimension 1
```
Any suggestions?
在跑长跟踪时报错了，这是什么原因呢?

**Comment by lzx1413** [comment]
长跟踪的时候会有search image 大小的变化，这个时候xy_ctr应该也是得随之变化的，配置文件里Denseboxhead的input_size_adapt需要设置为true

**Comment by lfxx** [comment]
> input_size_adapt

已解决．建议大佬在配置文件里默认加上该参数，不然一跑就报错了

**Comment by lfxx** [comment]
> 长跟踪的时候会有search image 大小的变化，这个时候xy_ctr应该也是得随之变化的，配置文件里Denseboxhead的input_size_adapt需要设置为true

已解决．建议大佬在配置文件里默认加上该参数，不然一跑就报错了

**Comment by lzx1413** [comment]
> > 长跟踪的时候会有search image 大小的变化，这个时候xy_ctr应该也是得随之变化的，配置文件里Denseboxhead的input_size_adapt需要设置为true
> 
> 已解决．建议大佬在配置文件里默认加上该参数，不然一跑就报错了

ok
