### ISSUE TITLE
TensorRT version

### ISSUE THREAD

**Issue by lfxx** [MegviiDetection/video_analyst#188]
Want to know the version of tensorrt the repo use.When i use tensorrt,version 7.2.3.4,get the error below:
```
[TensorRT] ERROR: coreReadArchive.cpp (41) - Serialization Error in verifyHeader: 0 (Version tag does not match. Note: Current Version: 96, Serialized Engine Version: 89)
[TensorRT] ERROR: INVALID_STATE: std::exception
[TensorRT] ERROR: INVALID_CONFIG: Deserialize the cuda engine failed.
Traceback (most recent call last):
  File "sot_video_online.py", line 139, in <module>
    main(args)
  File "sot_video_online.py", line 83, in main
    model = model_builder.build(task, task_cfg.model)
  File "/home/siamfcpps/videoanalyst/model/builder.py", line 39, in build
    losses)
  File "/home/siamfcpps/videoanalyst/model/task_model/builder.py", line 50, in build
    task_module.update_params()
  File "/home/siamfcpps/videoanalyst/model/task_model/taskmodel_impl/siamese_track.py", line 208, in update_params
    torch.load(self._hyper_params["trt_fea_model_path"]))
  File "/data/.conda/envs/interact/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1037, in load_state_dict
    load(self)
  File "/data/.conda/envs/interact/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1032, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
  File "/data/.conda/envs/interact/lib/python3.6/site-packages/torch2trt-0.2.0-py3.6.egg/torch2trt/torch2trt.py", line 443, in _load_from_state_dict
AttributeError: 'NoneType' object has no attribute 'create_execution_context'
```
seems that the tensorRT version is not same with the repo's.

**Comment by lzx1413** [comment]
we install trt from https://github.com/researchmm/TracKit/blob/master/lib/tutorial/install_trt.md, the version is  TensorRT-7.0.0.11

**Comment by lfxx** [comment]
> we install trt from https://github.com/researchmm/TracKit/blob/master/lib/tutorial/install_trt.md, the version is TensorRT-7.0.0.11

can tensorrt been used in long-term track.i modify the siamfcpp_googlenet.yaml file as below:
```
test:
  track:
    exp_name: &TEST_NAME "siamfcpp_googlenet_votlt"
    exp_save: &TEST_SAVE "logs"
    model:
      backbone:
        name: "Inception3"
        Inception3:
          crop_pad: 4
          pruned: True
      losses:
        names: []
      task_head:
        name: "DenseboxHead"
        DenseboxHead:
          total_stride: 8
          score_size: &SCORE_SIZE_TEST 19
          x_size: &X_SIZE_TEST 303
          num_conv3x3: &NUM_CONV3x3 2
          head_conv_bn: [False, False]
          input_size_adapt: True
      task_model:
        name: "SiamTrack"
        SiamTrack:
          pretrain_model_path: "models/siamfcpp-googlenet-vot-md5_f2680ba074213ee39d82fcb84533a1a6.pkl"
          trt_mode: True
          trt_fea_model_path: "models/siamfcpp-googlenet-vot-fea-md5_eef319.trt"
          trt_track_model_path: "models/siamfcpp-googlenet-vot-track-fea-md5_700273.trt"
    pipeline:
      name: "SiamFCppLTTracker"
      SiamFCppLTTracker:
        test_lr: 0.58
        window_influence: 0.21
        penalty_k: 0.08
        x_size: *X_SIZE_TEST
        num_conv3x3: *NUM_CONV3x3
```
But i ran into error below:
```
[TensorRT] WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
[TensorRT] WARNING: TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
[TensorRT] WARNING: TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
[TensorRT] WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.
[TensorRT] WARNING: TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
[TensorRT] WARNING: TensorRT was linked against cuDNN 7.6.3 but loaded cuDNN 7.6.2
[TensorRT] WARNING: Current optimization profile is: 0. Please ensure there are no enqueued operations pending in this context prior to switching profiles
2021-04-08 10:52:10.252 | INFO     | videoanalyst.model.task_model.taskmodel_impl.siamese_track:update_params:212 - loading trt model succefully
2021-04-08 10:52:10.290 | INFO     | __main__:main:89 - Starting from video frame image files...
2021-04-08 10:52:10.323 | DEBUG    | __main__:main:95 - frame: 2
2021-04-08 10:52:10.417 | DEBUG    | __main__:main:122 - pipeline initialized with bbox : [968.0, 184.0, 630.0, 896.0]
2021-04-08 10:52:10.439 | DEBUG    | __main__:main:95 - frame: 3
2021-04-08 10:52:10.494 | DEBUG    | __main__:main:95 - frame: 4
2021-04-08 10:52:10.534 | DEBUG    | __main__:main:95 - frame: 5
2021-04-08 10:52:10.579 | DEBUG    | __main__:main:95 - frame: 6
2021-04-08 10:52:10.615 | DEBUG    | __main__:main:95 - frame: 7
2021-04-08 10:52:10.654 | DEBUG    | __main__:main:95 - frame: 8
2021-04-08 10:52:10.664 | WARNING  | videoanalyst.pipeline.tracker_impl.siamfcpp_lt_track:_postprocess_box:422 - return old position
2021-04-08 10:52:10.664 | INFO     | videoanalyst.pipeline.tracker_impl.siamfcpp_lt_track:track:289 - lost target
2021-04-08 10:52:10.694 | DEBUG    | __main__:main:95 - frame: 9
Traceback (most recent call last):
  File "sot_video_online.py", line 130, in <module>
    main(args)
  File "sot_video_online.py", line 98, in main
    rect_pred = pipeline.update(frame)
  File "/home/longmao/workspace/siamfcpps/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py", line 326, in update
    update_state=True)
  File "/home/longmao/workspace/siamfcpps/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py", line 261, in track
    score, box_wh, target_sz, scale_x)
  File "/home/longmao/workspace/siamfcpps/videoanalyst/pipeline/tracker_impl/siamfcpp_lt_track.py", line 382, in _postprocess_score
    1 - 0.001) + self._state['lost_search_window'] * 0.001
ValueError: operands could not be broadcast together with shapes (361,) (961,) 
```
Any suggestions will be appreciated.

**Comment by lzx1413** [comment]
While using the long-term tracker, the search windows size will be enlarged if the track is lost. However, the trt version has been set to process images with const shape.  You can tryto dump the trt model with shape adaptive mode to solve this problem

**Comment by lfxx** [comment]
> While using the long-term tracker, the search windows size will be enlarged if the track is lost. However, the trt version has been set to process images with const shape. You can try to dump the trt model with shape adaptive mode to solve this problem

Thanks for your kindly reply.Where should i modify to change the dump method of trt model?I am noob on tensorrt.

**Comment by lzx1413** [comment]
We dump the trt model with fix input size here https://github.com/MegviiDetection/video_analyst/blob/f4d1bccb1c698961fed3cb70808f1177fab13bdd/main/cvt_trt.py#L67, you can change it with the larger size to deal with the lost condition.

**Comment by lfxx** [comment]
> We dump the trt model with fix input size here
> 
> https://github.com/MegviiDetection/video_analyst/blob/f4d1bccb1c698961fed3cb70808f1177fab13bdd/main/cvt_trt.py#L67
> 
> , you can change it with the larger size to deal with the lost condition.

Resolved.Thanks!
