### ISSUE TITLE
when I test in VOT,it always has a error. please help me

### ISSUE THREAD

**Issue by hekaijie123** [MegviiDetection/video_analyst#217]
when I test in VOT, it worked fine at first, but failed after some tests.Here are some information for when something goes wrong.

2021-12-12 05:07:47.807 | INFO     | videoanalyst.engine.tester.tester_impl.vot:track_single_video:296 - (59) Video: zebrafish1   Time: 2.5s Speed: 151.2fps Lost: 5 
  2%|█▍                                                                                 | 1/60 [28:21<27:53:19, 1701.68s/it]2021-12-12 05:07:47.808 | INFO     | videoanalyst.engine.tester.tester_impl.vot:run_tracker:147 - Total Lost: 120
2021-12-12 05:07:47.808 | INFO     | videoanalyst.engine.tester.tester_impl.vot:run_tracker:148 - Mean Speed: 176.03 FPS
loading VOT2018:   0%|                                              | 0/4 [00:00<?, ?it/s, homepage]
Traceback (most recent call last):                                  | 0/4 [00:00<?, ?it/s, homepage]
  File "main/test.py", line 77, in <module>
    tester.test()
  File "/home/hkj/Desktop/video_analyst/videoanalyst/engine/tester/tester_impl/vot.py", line 89, in test
    test_result_dict = self.evaluation()
  File "/home/hkj/Desktop/video_analyst/videoanalyst/engine/tester/tester_impl/vot.py", line 191, in evaluation
    dataset = vot_benchmark.VOTDataset(
  File "/home/hkj/Desktop/video_analyst/videoanalyst/evaluation/vot_benchmark/pysot/datasets/vot.py", line 113, in __init__
    video, dataset_root, meta_data[video]['video_dir'],
TypeError: string indices must be integers
100%|███████████████████████████████████████████████████████████████████████████████████████| 60/60 [28:21<00:00, 28.36s/it]

**Comment by hekaijie123** [comment]
The problem has been resolved because my vot2018.json file is corrupted.
