### ISSUE TITLE
SAT training problem

### ISSUE THREAD

**Issue by DTM3302** [MegviiDetection/video_analyst#92]
Hi，I'm sorry to bother you again。When i train SAT, and i set  num_processes=4, num_workers=16 in sat_res50_davis17.yaml。Unfortunately，it  was RuntimeError: 
Traceback (most recent call last):
  File "./main/dist_train_sat.py", line 211, in <module>
    join=True)
  File "/home/yanyi/miniconda3/envs/touch-env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 171, in spawn
    while not spawn_context.join():
  File "/home/yanyi/miniconda3/envs/touch-env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception:

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/yanyi/miniconda3/envs/touch-env/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/yanyi/PaperProject_chen/video_analyst-master/main/dist_train_sat.py", line 121, in run_dist_training
    dist_utils.synchronize()
  File "/home/yanyi/PaperProject_chen/video_analyst-master/videoanalyst/utils/dist_utils.py", line 81, in synchronize
    dist.barrier()
  File "/home/yanyi/miniconda3/envs/touch-env/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 1489, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:410, unhandled cuda error, NCCL version 2.4.8

And i set the num_processes=1,it start trianing, but out of  CUDA memory.

**Comment by lzx1413** [comment]
what's the version of your pytorch and cuda?

**Comment by DTM3302** [comment]
torch：1.4.0
cuda9

**Comment by DTM3302** [comment]
sorry my cuda version is 10.1

**Comment by lzx1413** [comment]
https://stackoverflow.com/questions/61075390/about-pytorch-nccl-error-unhandled-system-error-nccl-version-2-4-8, this may be helpful

**Comment by DTM3302** [comment]
Wuwu，I fellow his step  to set，it‘s still wrong. By the way, i only have one node ,and it has 4 GPUs.

**Comment by DTM3302** [comment]
Can SAT use DP training? it only trains on DDP?

**Comment by lzx1413** [comment]
We did not test the accuracy with DP mode. You can write one with DP mode according to [regular_trainer](https://github.com/MegviiDetection/video_analyst/blob/master/videoanalyst/engine/trainer/trainer_impl/regular_trainer.py) and start training with train.py

**Comment by DTM3302** [comment]
en，Thank you for your reply。Thank you for sharing your work。

**Comment by LANMNG** [comment]
in video_analyst/videoanalyst/data/utils/crop_track_pair.py line 201, why scale_curr_ = z_size / sc_? it may be scale_curr_ = x_size / sc_ ?  is what i find wrong or something else?

**Comment by lzx1413** [comment]
Because in the process of tracking, we assume that the size of the target is changing slowly. When generating image pairs for training, we'd like to resize the box of the target in current image to the same level with the template box. Then we will add extra random scale and shift change for the current image to process data augmentation.

**Comment by LANMNG** [comment]
I get it, thank you!
