### ISSUE TITLE
sh tools/sat/test/test_DAVIS2017.sh    error

### ISSUE THREAD

**Issue by guoxianda** [MegviiDetection/video_analyst#94]
when I  run the code ‘sh tools/sat/test/test_DAVIS2017.sh’    ,then there would be an error: 
2020-05-19 20:45:57.972 | INFO     | __main__:<module>:65 - Load experiment configuration at: /home/work/guoxianda/video_analyst/experiments/sat/test/sat_res50-davis17.yaml
2020-05-19 20:45:58.291 | INFO     | videoanalyst.model.module_base:update_params:62 - Load pretrained SiamTrack parameters from: /home/work/guoxianda/video_analyst/models/siamfcpp/siamfcpp-alexnet-vot-md5_18fd31a2f94b0296c08fff9b0f9ad240.pkl whose md5sum is 18fd31a2f94b0296c08fff9b0f9ad240
2020-05-19 20:46:16.195 | INFO     | videoanalyst.model.module_base:update_params:62 - Load pretrained SatVOS parameters from: /home/work/guoxianda/video_analyst/models/sat/sat_res50_davis17_b81fa.pkl whose md5sum is 61900ceacf73cc10fcf242491cbb81fa
2020-05-19 20:46:16.204 | INFO     | videoanalyst.engine.tester.tester_impl.davis:run_tracker:94 - runing test on devices [device(type='cuda', index=0), device(type='cuda', index=1), device(type='cuda', index=2), device(type='cuda', index=3)]
2020-05-19 20:46:16.204 | INFO     | videoanalyst.engine.tester.tester_impl.davis:run_tracker:96 - Using dataset DAVIS2017 at: /home/work/guoxianda/video_analyst/datasets/DAVIS
  0%|                                                                         | 0/30 [00:00<?, ?it/s]2020-05-19 20:46:17.498 | INFO     | videoanalyst.engine.tester.tester_impl.davis:run_tracker:125 - process:0, start:0, end:8
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "./main/test.py", line 80, in <module>
    tester.test()
  File "/home/work/guoxianda/video_analyst/videoanalyst/engine/tester/tester_impl/davis.py", line 83, in test
    self.run_tracker()
  File "/home/work/guoxianda/video_analyst/videoanalyst/engine/tester/tester_impl/davis.py", line 126, in run_tracker
    proc.start()
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/work/anaconda3/envs/venv3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 324, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: error executing torch_shm_manager at "/home/work/anaconda3/envs/venv3/lib/python3.6/site-packages/torch/bin/torch_shm_manager" at /pytorch/torch/lib/libshm/core.cpp:99

  Any solutions to this?  thank you very much! looking forward to your reply!

**Comment by lzx1413** [comment]
"torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory"
which version of your pytorch and cuda?

**Comment by guoxianda** [comment]
> "torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory"
> which version of your pytorch and cuda?

thank you for your reply！ my cuda is 9.0  and pytorch is 1.4.0

**Comment by lzx1413** [comment]
It seems that we need cuda 10.1 for libcudart.so.10.1

**Comment by guoxianda** [comment]
> It seems that we need cuda 10.1 for libcudart.so.10.1

thank you very much. cloud you tell me how to run the test.py in cpu?

**Comment by lzx1413** [comment]
set the deive_num 0 in the config file
